// Generated by CoffeeScript 1.9.0
(function() {
  var Promise, asyncArrayReturn, base, defineMemoizedPerInstanceProperty, promisify, promisifyArray, prop, proxyAll, proxyBuilder, __doc__, _i, _j, _len, _len1, _ref, _ref1,
    __slice = [].slice;

  __doc__ = "If you use this library then if you put `.promise` after a Node-style async\nfunction, it will turn it into a function that returns a Promise instead of\ntaking a callback.\n\nEx.\n  promisify = require 'instapromise'\n  p = fs.readFile.promise \"/tmp/hello\", 'utf8'\n  p.then(console.log)\n\nIf you want to promisify methods, use `.promise` after the object and before\nthe method name.\n\nEx.\n  promisify = require 'instapromise'\n  p = fs.promise.readFile \"/tmp/hello\", 'utf8'\n  p.then(console.log)\n\nThis code is based on the proxying code used in fibrous.\nhttps://github.com/goodeggs/fibrous/blob/master/src/fibrous.coffee\n";

  Promise = require('native-or-bluebird');

  promisify = require('./thenify');

  asyncArrayReturn = function(nodeStyleAsyncFunction) {
    "Transforms a Node-style async function that has multiple passed values\n(ex. (err, result, result2, result3)) into one that only has err and then\nan Array of those values (ex. (err, [result, result2, result3])) to\nconform to the (err, result) convention";
    return function() {
      var args, callback, _i;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), callback = arguments[_i++];
      args.push(function() {
        var cbArgs, err;
        err = arguments[0], cbArgs = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        return typeof callback === "function" ? callback(err, cbArgs) : void 0;
      });
      return nodeStyleAsyncFunction.apply(this, args);
    };
  };

  promisifyArray = function(nodeStyleAsyncFunction) {
    return promisify(asyncArrayReturn(nodeStyleAsyncFunction));
  };

  proxyAll = function(src, target, proxyFn) {
    var key, _fn, _i, _len, _ref;
    _ref = Object.keys(src);
    _fn = function(key) {
      if (Object.prototype[key] != null) {
        return;
      }
      if (Object.getOwnPropertyDescriptor(src, key).get != null) {
        return;
      }
      if (typeof src[key] !== 'function') {
        return;
      }
      return target[key] = proxyFn(key);
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      _fn(key);
    }
    return target;
  };

  proxyBuilder = function(prop) {
    return function(that) {
      var func, result;
      result = typeof that === 'function' ? (func = (function() {
        switch (prop) {
          case 'promise':
            return promisify(that);
          case 'promiseArray':
            return promisifyArray(that);
          default:
            throw new Error("Unknown proxy property `" + prop + "`");
        }
      })(), Object.getPrototypeOf(that) !== Function.prototype ? func.__proto__ = Object.getPrototypeOf(that)[prop] : void 0, func) : Object.create(Object.getPrototypeOf(that) && Object.getPrototypeOf(that)[prop] || Object.prototype);
      result.that = that;
      return proxyAll(that, result, function(key) {
        return function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return this.that[key][prop].apply(this.that, args);
        };
      });
    };
  };

  defineMemoizedPerInstanceProperty = function(target, propertyName, factory) {
    var cacheKey;
    cacheKey = "__instapromise" + propertyName + "__";
    return Object.defineProperty(target, propertyName, {
      enumerable: false,
      set: function(value) {
        delete this[cacheKey];
        return Object.defineProperty(this, propertyName, {
          value: value,
          writable: true,
          configurable: true,
          enumerable: true
        });
      },
      get: function() {
        if (!(Object.prototype.hasOwnProperty.call(this, cacheKey) && this[cacheKey])) {
          Object.defineProperty(this, cacheKey, {
            value: factory(this),
            writable: true,
            configurable: true,
            enumerable: false
          });
        }
        return this[cacheKey];
      }
    });
  };

  _ref = [Object.prototype, Function.prototype];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    base = _ref[_i];
    _ref1 = ['promise', 'promiseArray'];
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      prop = _ref1[_j];
      defineMemoizedPerInstanceProperty(base, prop, proxyBuilder(prop));
    }
  }

  module.exports = {
    __doc__: __doc__,
    Promise: Promise,
    promisify: promisify,
    promisifyArray: promisifyArray
  };

}).call(this);
