// Generated by CoffeeScript 1.9.0
(function() {
  var base, defineMemoizedPerInstanceProperty, promisify, proxyAll, proxyBuilder, __doc__, _i, _len, _ref,
    __slice = [].slice;

  __doc__ = "If you use this library then if you put `.promise` after a Node-style async\nfunction, it will turn it into a function that returns a Promise instead of\ntaking a callback.\n\nEx.\n  promisify = require 'instapromise'\n  p = fs.readFile.promise \"/tmp/hello\", 'utf8'\n  p.then(console.log)\n\nIf you want to promisify methods, use `.promise` after the object and before\nthe method name.\n\nEx.\n  promisify = require 'instapromise'\n  p = fs.promise.readFile \"/tmp/hello\", 'utf8'\n  p.then(console.log)\n\nThis code is based on the proxying code used in fibrous.\nhttps://github.com/goodeggs/fibrous/blob/master/src/fibrous.coffee\n";

  promisify = require('bluebird').promisify;

  module.exports = promisify;

  proxyAll = function(src, target, proxyFn) {
    var key, _fn, _i, _len, _ref;
    _ref = Object.keys(src);
    _fn = function(key) {
      if (Object.prototype[key] != null) {
        return;
      }
      if (Object.getOwnPropertyDescriptor(src, key).get != null) {
        return;
      }
      if (typeof src[key] !== 'function') {
        return;
      }
      return target[key] = proxyFn(key);
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      _fn(key);
    }
    return target;
  };

  proxyBuilder = function() {
    return function(that) {
      var func, result;
      result = typeof that === 'function' ? (func = promisify(that), Object.getPrototypeOf(that) !== Function.prototype ? func.__proto__ = Object.getPrototypeOf(that).promise : void 0, func) : Object.create(Object.getPrototypeOf(that) && Object.getPrototypeOf(that).promise || Object.prototype);
      result.that = that;
      return proxyAll(that, result, function(key) {
        return function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return this.that[key].promise.apply(this.that, args);
        };
      });
    };
  };

  defineMemoizedPerInstanceProperty = function(target, propertyName, factory) {
    var cacheKey;
    cacheKey = "__fibrous" + propertyName + "__";
    return Object.defineProperty(target, propertyName, {
      enumerable: false,
      set: function(value) {
        delete this[cacheKey];
        return Object.defineProperty(this, propertyName, {
          value: value,
          writable: true,
          configurable: true,
          enumerable: true
        });
      },
      get: function() {
        if (!(Object.prototype.hasOwnProperty.call(this, cacheKey) && this[cacheKey])) {
          Object.defineProperty(this, cacheKey, {
            value: factory(this),
            writable: true,
            configurable: true,
            enumerable: false
          });
        }
        return this[cacheKey];
      }
    });
  };

  _ref = [Object.prototype, Function.prototype];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    base = _ref[_i];
    defineMemoizedPerInstanceProperty(base, 'promise', proxyBuilder());
  }

}).call(this);
