// Generated by CoffeeScript 1.9.0
(function() {
  var SomeClass, promisify, request, sc;

  promisify = require('.');

  SomeClass = (function() {
    function SomeClass(_at_x) {
      this.x = _at_x;
      console.log("Made a SomeClass instance with x=" + this.x);
    }

    SomeClass.prototype.nodeStyleAsyncMethod = function(y, callback) {
      console.log("Adding " + this.x + " and " + y);
      return callback(null, this.x + y);
    };

    return SomeClass;

  })();

  module.exports = {
    SomeClass: SomeClass
  };

  if (require.main === module) {
    sc = new SomeClass(3);
    sc.promise.nodeStyleAsyncMethod(5).then(console.log);
    sc.promiseArray.nodeStyleAsyncMethod(5).then(console.log);
    request = require('request');
    request.promise.get('http://cdc03.com/').then(function(response, body) {
      return console.log("body1=", body, "or=", response.body);
    });
    request.promiseArray.get("http://cdc03.com/").then(function(_arg) {
      var body, response;
      response = _arg[0], body = _arg[1];
      return console.log("body2=", body);
    });
  }

}).call(this);
